[tox]
skipsdist = True
envlist = py311, py312, flake8
skip_missing_interpreters = True

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 tests

[testenv]
allowlist_externals = *
deps =
    c7n==0.9.49
    pytest
    pytest-cov
    coverage
    moto
    yamllint
setenv =
    PYTHONPATH = {toxinidir}
    AWS_DEFAULT_REGION = us-east-1
commands =
    yamllint .
    custodian validate policies/sg.yml policies/s3.yml
    pytest --basetemp={envtmpdir} -vv --cov-report term --cov-report html:htmlcov --cov-report xml --cov={toxinidir}
